#!/bin/bash

# Define the list of nodes and their IP addresses
nodes=("node1" "node2" "node3")
ip_addresses=("XXXXXX" "XXXXXX" "XXXXXX")

# Define your SSH password (consider using SSH key authentication for security)
password="XXXXXX"

# Define an array of new users and their passwords
new_users=("babafarooq" "newuser1" "newuser2")
passwords=("Babafarooq001@" "Password1@" "Password2@")

# Function to create a new user with a password
create_new_user() {
    local node=$1
    local ip=$2
    local new_user=$3
    local new_user_password=$4

    echo "Creating user $new_user on $node ($ip):"

    # Check if the user already exists
    if sshpass -p "$password" ssh "$ip" id "$new_user" &>/dev/null; then
        echo "User $new_user already exists on $node."
    else
        # Use SSH to create the new user with a home directory and set the password
        sshpass -p "$password" ssh "$ip" "sudo useradd -m -d /home/$new_user $new_user; echo -e '$new_user_password\n$new_user_password' | sudo passwd $new_user"

        if [ $? -eq 0 ]; then
            echo "User $new_user created with the password on $node."
        else
            echo "Failed to create user $new_user on $node."
        fi
    fi

    echo -e "\n-----------------------------------------\n"
}

# Create the new users on the nodes
for ((i=0; i<${#nodes[@]}; i++)); do
    node="${nodes[i]}"
    ip="${ip_addresses[i]}"
    
    for ((j=0; j<${#new_users[@]}; j++)); do
        user="${new_users[j]}"
        password="${passwords[j]}"
        create_new_user "$node" "$ip" "$user" "$password"
    done
done
