#!/bin/bash

# Update and upgrade system
sudo apt update && sudo apt upgrade -y

# Download and add VirtualBox signing key to keyring
sudo apt-get purge virtualbox*
sudo apt-get autoremove
sudo apt-get purge virtualbox* && sudo apt-get autoremove
dpkg -l | grep virtualbox
deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian <mydist> contrib
sudo apt-get update
sudo apt-get install virtualbox-6.1

# Update again to refresh package lists
sudo apt update && sudo apt upgrade -y
echo "VirtualBox has been installed successfully."
sleep 10

